"""
AI 洞察模型 (AI Insight Model)

定义 AI 分析结果的表结构，存储异常检测、根因分析、智能对话等 AI 引擎产生的洞察结果。
该模型支持多种洞察类型，并与主机和告警进行关联，为运维决策提供智能支持。

Defines the table structure for AI analysis results, storing insights generated by the AI engine
such as anomaly detection, root cause analysis, and intelligent conversations.
Provides intelligent support for operational decision-making.
"""
from datetime import datetime
from typing import Optional

from sqlalchemy import Integer, String, Text, DateTime, JSON, ForeignKey, func
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class AIInsight(Base):
    """
    AI 洞察表 (AI Insight Table)
    
    存储 AI 引擎产生的各种分析结果和洞察信息，包括异常检测、根因分析、智能对话等。
    每个洞察包含类型、严重程度、分析内容以及与主机和告警的关联关系。
    
    Table for storing various analysis results and insights generated by the AI engine,
    including anomaly detection, root cause analysis, and intelligent conversations.
    Each insight contains type, severity, analysis content, and relationships with hosts and alerts.
    """
    __tablename__ = "ai_insights"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)  # 主键 ID (Primary Key ID)
    insight_type: Mapped[str] = mapped_column(String(50), nullable=False)  # 洞察类型：异常/根因/对话 (Insight Type: anomaly/root_cause/chat)
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="info")  # 严重程度：信息/警告/严重 (Severity: info/warning/critical)
    title: Mapped[str] = mapped_column(String(500), nullable=False)  # 洞察标题 (Insight Title)
    summary: Mapped[str] = mapped_column(Text, nullable=False)  # 洞察摘要描述 (Insight Summary)
    details: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)  # 完整分析结果 JSON 数据 (Complete Analysis Results in JSON)
    related_host_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("hosts.id"), nullable=True)  # 关联主机 ID (Related Host ID)
    related_alert_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("alerts.id"), nullable=True)  # 关联告警 ID (Related Alert ID)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="new")  # 处理状态：新建/已确认/已解决 (Processing Status: new/acknowledged/resolved)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())  # 创建时间 (Creation Time)
