{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nightmend.fullname" . }}-redis
  labels:
    {{- include "nightmend.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: tcp-redis
      protocol: TCP
      name: tcp-redis
  selector:
    {{- include "nightmend.redis.selectorLabels" . | nindent 4 }}
{{- end }}
